// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `smsservice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.m51das.ice.sms.sv;

public interface SMSService extends Ice.Object,
                                    _SMSServiceOperations, _SMSServiceOperationsNC
{
    public static final String ice_staticId = "::sms::SMSService";

    public static final long serialVersionUID = -117036064L;
}
