// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.5
//
// <auto-generated>
//
// Generated from file `bookservice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.m51das.ice.book.sv;

public interface OnlineBook extends Ice.Object,
                                    _OnlineBookOperations, _OnlineBookOperationsNC
{
    public static final String ice_staticId = "::book::OnlineBook";

    public static final long serialVersionUID = -1468137134L;
}
